# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8G -Xms8G --enable-native-access=ALL-UNNAMED -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
org.gradle.parallel=true
org.gradle.daemon=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Fabric API
fabric_api_version=0.138.4+1.21.10

# Dependencies
masa_mc_version=1.21.10
malilib_version = 0.26.8
litematica_version = 0.24.7

# Mod Properties
mod_version=1.0.9
maven_group=com.andrews.st2downloader
archives_base_name=st2-downloader
