# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Mod properties
mod.version=1.0.15
mod.group=com.andrews.archivedownloader
mod.id=archive-downloader
mod.name=Archive Downloader

# Global dependencies
deps.fabric_loader=0.18.5

publish.modrinth=6PRa8cm7
publish.curseforge=1447777

loomx.loom_version=1.15-SNAPSHOT